2022-10-27 14:12:12.200 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
2022-10-27 14:12:12.202 | INFO     | sc2.controller:create_game:37 - Creating new game
2022-10-27 14:12:12.203 | INFO     | sc2.controller:create_game:38 - Map:     RomanticideAIE
2022-10-27 14:12:12.205 | INFO     | sc2.controller:create_game:39 - Players: Bot Turtles(Terran), Computer VeryHard(Random, RandomBuild)
2022-10-27 14:12:12.207 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
2022-10-27 14:12:21.433 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
2022-10-27 14:12:21.435 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot Turtles(Terran)
2022-10-27 14:12:22.035 | 00:00    0ms    0M    0G  12/ 15U [Version] 5.0.10.88500
2022-10-27 14:12:22.037 | 00:00    0ms    0M    0G  12/ 15U [Version] 5.0.6 Balance mod recognized.
2022-10-27 14:12:22.106 | 00:00    0ms    0M    0G  12/ 15U [ZoneManager] Map set to: MapName.RomanticideLE from name: Romanticide AIE and hash: 3756032.
2022-10-27 14:12:22.840 | ERROR    | sc2.main:initialize_first_step:140 - Caught unknown exception in AI on_start: 'MacroBio' object has no attribute 'chat_send'
Traceback (most recent call last):

  File "C:\Users\sword\OneDrive\Desktop\27turtles\run.py", line 18, in <module>
    main()
    └ <function main at 0x00000260A2355240>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\run.py", line 13, in main
    result, opponentid = run_ladder_game(bot)
                         │               └ <sc2.player.Bot object at 0x00000260A2350070>
                         └ <function run_ladder_game at 0x00000260FFC79360>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\ladder.py", line 39, in run_ladder_game
    return stand_alone_game(bot), None
           │                └ <sc2.player.Bot object at 0x00000260A2350070>
           └ <function stand_alone_game at 0x000002609FC295A0>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\ladder.py", line 168, in stand_alone_game
    return sc2.main.run_game(sc2.maps.get(map_name), [bot, Computer(Race.Random, Difficulty.VeryHard)], realtime=False,)
           │   │    │        │   │    │   │           │    │        │    │       │          └ <Difficulty.VeryHard: 7>
           │   │    │        │   │    │   │           │    │        │    │       └ <enum 'Difficulty'>
           │   │    │        │   │    │   │           │    │        │    └ <Race.Random: 4>
           │   │    │        │   │    │   │           │    │        └ <enum 'Race'>
           │   │    │        │   │    │   │           │    └ <class 'sc2.player.Computer'>
           │   │    │        │   │    │   │           └ <sc2.player.Bot object at 0x00000260A2350070>
           │   │    │        │   │    │   └ 'RomanticideAIE'
           │   │    │        │   │    └ <function get at 0x000002609FCD8550>
           │   │    │        │   └ <module 'sc2.maps' from 'C:\\Users\\sword\\OneDrive\\Desktop\\27turtles\\sc2\\maps.py'>
           │   │    │        └ <module 'sc2' from 'C:\\Users\\sword\\OneDrive\\Desktop\\27turtles\\sc2\\__init__.py'>
           │   │    └ <function run_game at 0x000002609FDB8E50>
           │   └ <module 'sc2.main' from 'C:\\Users\\sword\\OneDrive\\Desktop\\27turtles\\sc2\\main.py'>
           └ <module 'sc2' from 'C:\\Users\\sword\\OneDrive\\Desktop\\27turtles\\sc2\\__init__.py'>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\sc2\main.py", line 496, in run_game
    result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
                     │       │   │          │             │          └ {'realtime': False}
                     │       │   │          │             └ [<sc2.player.Bot object at 0x00000260A2350070>, <sc2.player.Computer object at 0x00000260A236E0E0>]
                     │       │   │          └ Map(C:\Program Files (x86)\StarCraft II\maps\RomanticideAIE.SC2Map)
                     │       │   └ <function _host_game at 0x000002609FDB8A60>
                     │       └ <function run at 0x000002608193D7E0>
                     └ <module 'asyncio' from 'C:\\Users\\sword\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Users\sword\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object _host_game at 0x00000260A2306E30>
           │    └ <function BaseEventLoop.run_until_complete at 0x000002608193F1C0>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\sword\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000260819EBBE0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\sword\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\sword\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000026081940CA0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\sword\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002608189C280>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\sword\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\sc2\main.py", line 369, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, game_time_limit, rgb_render_config)
                   │          │           │       │         │           │                └ None
                   │          │           │       │         │           └ None
                   │          │           │       │         └ None
                   │          │           │       └ False
                   │          │           └ <sc2.client.Client object at 0x00000260A236DA80>
                   │          └ [<sc2.player.Bot object at 0x00000260A2350070>, <sc2.player.Computer object at 0x00000260A236E0E0>]
                   └ <function _play_game at 0x000002609FDB88B0>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\sc2\main.py", line 226, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, game_time_limit)
                   │             │       │          │      │   │         └ None
                   │             │       │          │      │   └ False
                   │             │       │          │      └ <turtles.bot.Turtles object at 0x0000026081936C80>
                   │             │       │          └ <sc2.player.Bot object at 0x00000260A2350070>
                   │             │       └ 1
                   │             └ <sc2.client.Client object at 0x00000260A236DA80>
                   └ <function _play_game_ai at 0x000002609FDB8700>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\sc2\main.py", line 145, in _play_game_ai
    result = await initialize_first_step()
                   └ <function _play_game_ai.<locals>.initialize_first_step at 0x00000260A2355D80>

> File "C:\Users\sword\OneDrive\Desktop\27turtles\sc2\main.py", line 136, in initialize_first_step
    await ai.on_start()
          │  └ <function KnowledgeBot.on_start at 0x00000260A21C6C20>
          └ <turtles.bot.Turtles object at 0x0000026081936C80>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\sharpy\knowledges\knowledge_bot.py", line 71, in on_start
    await self.knowledge.start()
          │    │         └ <function Knowledge.start at 0x000002609FE3B010>
          │    └ <sharpy.knowledges.knowledge.Knowledge object at 0x00000260FF906590>
          └ <turtles.bot.Turtles object at 0x0000026081936C80>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\sharpy\knowledges\knowledge.py", line 151, in start
    await manager.post_start()
          │       └ <function ActManager.post_start at 0x000002609FC6D000>
          └ <sharpy.managers.core.act_manager.ActManager object at 0x00000260A2487CD0>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\sharpy\managers\core\act_manager.py", line 25, in post_start
    self._act = await self._act_or_func()
    │                 │    └ <bound method Turtles.create_plan of <turtles.bot.Turtles object at 0x0000026081936C80>>
    │                 └ <sharpy.managers.core.act_manager.ActManager object at 0x00000260A2487CD0>
    └ <sharpy.managers.core.act_manager.ActManager object at 0x00000260A2487CD0>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\turtles\bot.py", line 48, in create_plan
    self.build = MacroBio()
    │    │       └ <class 'turtles.biobuild.MacroBio'>
    │    └ <function BotAI.build at 0x000002609FBABE20>
    └ <turtles.bot.Turtles object at 0x0000026081936C80>

  File "C:\Users\sword\OneDrive\Desktop\27turtles\turtles\biobuild.py", line 39, in __init__
    self.chat_send("GLHF!")
    └ <turtles.biobuild.MacroBio object at 0x00000260A3DA4190>

AttributeError: 'MacroBio' object has no attribute 'chat_send'
2022-10-27 14:12:22.992 | ERROR    | sc2.main:initialize_first_step:141 - Resigning due to previous error
2022-10-27 14:12:22.993 | Result: Defeat
2022-10-27 14:12:22.994 | Duration: 00:00
2022-10-27 14:12:22.995 | Step time avg: 0
2022-10-27 14:12:22.995 | Step time max: 0
2022-10-27 14:12:22.996 | [LostUnitsContents] My lost units minerals and gas: (0, 0)
2022-10-27 14:12:22.999 | [LostUnitsContents] My lost units minerals by score: 0.0
2022-10-27 14:12:23.000 | [LostUnitsContents] Enemy lost units minerals and gas: (0, 0)
2022-10-27 14:12:23.001 | [LostUnitsContents] Enemy lost units minerals by score: 0.0
2022-10-27 14:12:23.002 | [GameAnalyzerEnd] Own units:
2022-10-27 14:12:23.003 | [GameAnalyzerEnd] Enemy units:
2022-10-27 14:12:23.003 | [GameAnalyzerEnd] Minerals max 0 Average 0
2022-10-27 14:12:23.005 | [GameAnalyzerEnd] Vespene max 0 Average 0
2022-10-27 14:12:23.006 | INFO     | sc2.main:_play_game:228 - Result for player 1 - Bot Turtles(Terran): Defeat
2022-10-27 14:12:23.979 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was Status.in_game)
2022-10-27 14:12:23.986 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.quit (was Status.launched)
2022-10-27 14:12:23.988 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at 52384...
2022-10-27 14:12:23.989 | INFO     | sc2.sc2process:kill_all:33 - kill_switch: Process cleanup for 1 processes
